// placeholder (regenerated by tools/build_portal.py)
#pragma once
#include <stdint.h>
struct PortalAsset { const char* path; const char* mime; const uint8_t* data; uint32_t len; };
extern const PortalAsset PORTAL_ASSETS[];
extern const int PORTAL_ASSET_COUNT;
